#!/bin/sh
# php-cs-fixer expects it's first parameter to be the command name
COMMAND=$1; shift
DIR=`git rev-parse --show-toplevel`
REPO_NAME=`basename $DIR`
php $DIR/vendor/bin/php-cs-fixer $COMMAND --config $DIR/.php-cs-fixer.php "$@"
